/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BinRouteImport } from './routes/bin'
import { Route as BooksRouteImport } from './routes/books'
import { Route as ComicsRouteImport } from './routes/comics'
import { Route as ImportRouteImport } from './routes/import'
import { Route as MoviesRouteImport } from './routes/movies'
import { Route as MusicRouteImport } from './routes/music'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VideogamesRouteImport } from './routes/videogames'
import { Route as CustomTypeIdRouteImport } from './routes/custom.$typeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BinRoute = BinRouteImport.update({
  id: '/bin',
  path: '/bin',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksRoute = BooksRouteImport.update({
  id: '/books',
  path: '/books',
  getParentRoute: () => rootRouteImport,
} as any)
const ComicsRoute = ComicsRouteImport.update({
  id: '/comics',
  path: '/comics',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesRoute = MoviesRouteImport.update({
  id: '/movies',
  path: '/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VideogamesRoute = VideogamesRouteImport.update({
  id: '/videogames',
  path: '/videogames',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomTypeIdRoute = CustomTypeIdRouteImport.update({
  id: '/custom/$typeId',
  path: '/custom/$typeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bin': typeof BinRoute
  '/books': typeof BooksRoute
  '/comics': typeof ComicsRoute
  '/import': typeof ImportRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/settings': typeof SettingsRoute
  '/videogames': typeof VideogamesRoute
  '/custom/$typeId': typeof CustomTypeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bin': typeof BinRoute
  '/books': typeof BooksRoute
  '/comics': typeof ComicsRoute
  '/import': typeof ImportRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/settings': typeof SettingsRoute
  '/videogames': typeof VideogamesRoute
  '/custom/$typeId': typeof CustomTypeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bin': typeof BinRoute
  '/books': typeof BooksRoute
  '/comics': typeof ComicsRoute
  '/import': typeof ImportRoute
  '/movies': typeof MoviesRoute
  '/music': typeof MusicRoute
  '/settings': typeof SettingsRoute
  '/videogames': typeof VideogamesRoute
  '/custom/$typeId': typeof CustomTypeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bin'
    | '/books'
    | '/comics'
    | '/import'
    | '/movies'
    | '/music'
    | '/settings'
    | '/videogames'
    | '/custom/$typeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bin'
    | '/books'
    | '/comics'
    | '/import'
    | '/movies'
    | '/music'
    | '/settings'
    | '/videogames'
    | '/custom/$typeId'
  id:
    | '__root__'
    | '/'
    | '/bin'
    | '/books'
    | '/comics'
    | '/import'
    | '/movies'
    | '/music'
    | '/settings'
    | '/videogames'
    | '/custom/$typeId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BinRoute: typeof BinRoute
  BooksRoute: typeof BooksRoute
  ComicsRoute: typeof ComicsRoute
  ImportRoute: typeof ImportRoute
  MoviesRoute: typeof MoviesRoute
  MusicRoute: typeof MusicRoute
  SettingsRoute: typeof SettingsRoute
  VideogamesRoute: typeof VideogamesRoute
  CustomTypeIdRoute: typeof CustomTypeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bin': {
      id: '/bin'
      path: '/bin'
      fullPath: '/bin'
      preLoaderRoute: typeof BinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books': {
      id: '/books'
      path: '/books'
      fullPath: '/books'
      preLoaderRoute: typeof BooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comics': {
      id: '/comics'
      path: '/comics'
      fullPath: '/comics'
      preLoaderRoute: typeof ComicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies': {
      id: '/movies'
      path: '/movies'
      fullPath: '/movies'
      preLoaderRoute: typeof MoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videogames': {
      id: '/videogames'
      path: '/videogames'
      fullPath: '/videogames'
      preLoaderRoute: typeof VideogamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom/$typeId': {
      id: '/custom/$typeId'
      path: '/custom/$typeId'
      fullPath: '/custom/$typeId'
      preLoaderRoute: typeof CustomTypeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BinRoute: BinRoute,
  BooksRoute: BooksRoute,
  ComicsRoute: ComicsRoute,
  ImportRoute: ImportRoute,
  MoviesRoute: MoviesRoute,
  MusicRoute: MusicRoute,
  SettingsRoute: SettingsRoute,
  VideogamesRoute: VideogamesRoute,
  CustomTypeIdRoute: CustomTypeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
